---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  type: webserver
spec:
 replicas: 2
 selector:
  matchLabels:
   type: webserver
 template:
  metadata:
   name: nginx-pod
   labels:
    type: webserver
  spec:
   containers:
    - name: mynginx
      image: nginx