---
apiVersion: v1
kind: Service
metadata:
 name: cluster-service
 labels:
  name: cluster-ip
spec:
 type: ClusterIP
 ports:
  - targetPort: 80
    port: 80
    nodePort: 30008
 selector:
  type: webserver
...