---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: result-voting-app
 labels:
  type: result-app
spec:
 replicas: 2
 selector:
  matchLabels:
   type: result-app
 template:
  metadata:
    name: result-voting-app-pod
    labels:
     type: result-app
  spec:
   containers:
     - name: result-voting-app-con
       image: dockersamples/examplevotingapp_result
...