---
apiVersion: v1
kind: Service
metadata:
 name: front-app-service
 labels:
  author: sandeep
spec:
 type: LoadBalancer
 ports:
  - targetPort: 80
    port: 80
    nodePort: 30008
 selector:
  type: voting-app