---
apiVersion: v1
kind: service
metadata:
 name: result-service
 labels:
  author: sandeep
spec:
 type: LoadBalancer
 ports:
  - targetPort: 80
    port: 80
    nodePort: 30009
 selector:
  type: result-app   