---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: worker-dep
 labels:
  type: worker
spec:
 replicas: 2
 selector:
  matchLabels:
   type: worker
 template:
  metadata:
   name: worker-dep-pod
   labels:
    type: worker
  spec:
   containers:
     - name: worker-con
       image: dockersamples/examplevotingapp_worker
...